theme: jekyll-theme-architect
title: Sparti AB
description: |
  Omtanke, Tillit och Måttfullhet
  
  Det är de grunderna som Sparti AB bygger på.
  Vi konsultar inom systemutveckling till vardags, men drömmer också om storslagna projekt för att göra världen mycket bättre.
context: /ideas
contact:
  mail: thobias.bergqvist@sparti.se
  name: Thobias Bergqvist
collections:
  ideas:
    output: true
    permalink: /:name
