theme: jekyll-theme-architect
title: Sparti
description: Omtanke, Tillit och Måttfullhet är de grunder som sparti baserat sin verksamhet på. Vi bedriver dels konsultverksamhet inom systemutveckling men vi drömmer även om grandiosa projekt för att förbättra världen.
contact:
  mail: thobias.bergqvist@sparti.se
  name: Thobias Bergqvist
collections:
  projects:
    output: true
    permalink: /:name
