theme: jekyll-theme-architect
title: Sparti AB
description: |
  Omtanke - Tillit - Måttfullhet
  
  Det är fundamentet som Sparti bygger på.
  Jag konsulterar inom systemutveckling till vardags, men drömmer också om storslagna projekt för att göra världen mycket bättre.
context: /ideer
contact:
  mail: thobias.bergqvist@sparti.se
  name: Thobias Bergqvist
collections:
  ideer:
    output: true
    permalink: /:name
