theme: jekyll-theme-architect
title: Sparti AB
description: |
  Omtanke, Tillit och Måttfullhet grundar som allt Sparti AB gör sig på.
  Dels konsultar vi inom systemutveckling men vi drömmer också om storslagna projekt för att göra världen mycket bättre.
context: /projects
contact:
  mail: thobias.bergqvist@sparti.se
  name: Thobias Bergqvist
collections:
  projects:
    output: true
    permalink: /:name
